### ISSUE TITLE
Why is (MonadIO m) => m (Maybe x) used instead of (MonadIO m, MonadPlus m) => m x

### ISSUE THREAD

**Issue by 2426021684** [ghcjs/ghcjs-dom#48]
Why is `(MonadIO m) => m (Maybe x)` used instead of `(MonadIO m, MonadPlus m) => m x`?

**Comment by hamishmack** [comment]
I have not used MonadPlus that way before.  Does it require us to use exceptions?  If so there might be performance implications.

I also like the fact that this code gives a compiler warning about the incomplete pattern matching:

```
Just element1 <- getElementById doc id1

getElementById doc id2 >>= \case
    Just element2 -> ...
```

Ideally the only functions that return `Maybe x` would be the ones where null can actually be returned (like `getElementById`), but we can only narrow it down based on the quality of the information in the IDL files the code is generated from.

**Comment by spl** [comment]
I'm not sure about the specific context of the question, but those types are two very different beasts:

* `f :: MonadIO m => m (Maybe x)`: The function `f` can indicate failure (`Nothing`) in its returned value, forcing the expression containing `f` to handle the failure case.
* `f :: (MonadIO m, MonadPlus m) => m x`: The function `f` indicates failure (`mzero` or `fail`) in the monad `m`, forcing the failure of the entire monadic expression containing `f`.

**Comment by 2426021684** [comment]
@spl They are very similar.
`f1 = runMaybeT f2`
`f2 = f1 >>= mfromMaybe`

**Comment by spl** [comment]
@2426021684: It's not clear to me what you're saying with those equations. Let me try to rephrase them below:

```haskell
import Control.Applicative
import Control.Monad
import Control.Monad.Trans.Maybe
import GHC.IO

mfromMaybe :: MonadPlus m => Maybe a -> m a
mfromMaybe = maybe mzero return

f1 :: MaybeT m a -> m (Maybe a)
f1 = runMaybeT

f2 :: MonadPlus m => m (Maybe b) -> m b
f2 x = x >>= mfromMaybe
```

First, `f1` and `f2` are not isomorphic:

```haskell
ghci> :t f1 . f2
f1 . f2 :: Monad m => MaybeT m (Maybe a) -> m (Maybe a)
ghci> :t f2 . f1
f2 . f1 :: MonadPlus m => MaybeT m b -> m b
```

Second, they do not handle “failure” in a similar way. Consider the following file, in which I use `f1` and `f2` with `Nothing` to indicate failure. (I don't have GHC 8.0, which has the `MonadPlus IO` instance, so this is written for GHC 7.10 using code from `base-4.9`.)

```haskell
mplusIO :: IO a -> IO a -> IO a
mplusIO m n = m `catchIOError` \ _ -> n
  where
    catchIOError :: IO a -> (IOError -> IO a) -> IO a
    catchIOError = catchException

instance Alternative IO where
  empty = fail "mzero"
  (<|>) = mplusIO

instance MonadPlus IO
    
main = do
  f1 $ MaybeT $ putStrLn "hello" >> return Nothing
  f2 $ putStrLn "good bye" >> return Nothing
```

The output is:

```
hello
good bye
main.hs: user error (mzero)
```

The failure of `f1` is ignored, but the failure of `f2` is throwing an exception in `IO`. You can, of course, catch the exception; however, you can't really say that `f1` and `f2` are similar, either in their types or their semantics.

**Comment by 2426021684** [comment]
@spl What I meant by similar is that you can convert between `MaybeT IO t`, `(MonadIO m) => m (Maybe t)`, `(MonadIO m) => MaybeT m t`, and `(MonadIO m, MonadPlus m) => m t` without loss. The `MonadPlus` instance of `IO` throws an exception on failure. The MonadPlus instance of `MaybeT IO` does not throw an exception. `runMaybeT` can convert `(MonadIO m, MonadPlus m) => m t` to `(MonadIO m) => m (Maybe t)`. `mfromMaybe` can convert a `Maybe t` value to an `(MonadPlus m) => m t`.`(MonadIO m, MonadPlus m) => m t` and `(MonadIO m) => m (Maybe t)` are isomorphic.

**Comment by 2426021684** [comment]
@hamishmack `MonadPlus` does not require exceptions. It is just like `Maybe` but instead of `Nothing` you use `mzero` and instead of `Just` you use `return`. `IO` is an instance of `MonadPlus` which throws an exception on `mzero`. `MaybeT IO` and `Maybe` are instances of `MonadPlus` which do not throw exceptions on `mzero`. `MaybeT IO` is both an instance of `MonadIO` and `MonadPlus`.

**Comment by spl** [comment]
@2426021684:

At the start, you suggested using `(MonadIO m, MonadPlus m) => m a` instead of `MonadIO m => m (Maybe a)`. These are clearly not isomorphic. (For simplicity and pedagogy without sacrificing meaning, let's use `IO a` instead of `MonadIO m => m a`.) Consider the following:

```haskell
-- An initial value
a1 :: IO (Maybe a)
a1 = return Nothing

-- Convert to IO a
a2 :: IO a
a2 = a1 >>= mfromMaybe

-- Convert back to IO (Maybe a)
a3 :: IO (Maybe a)
-- a3 = runMaybeT a2  -- Wrong type
a3 = fmap Just a2 `mplus` return Nothing
```

In GHCi:

```haskell
ghci> a1
Nothing
ghci> a3
Nothing
```

Okay, that conversion works. But what if we have an exception thrown in our initial value?

```haskell
-- Another initial value
b1 :: IO (Maybe a)
b1 = throwIO $ userError "exception"

-- Convert to IO a
b2 :: IO a
b2 = b1 >>= mfromMaybe

-- Convert back to IO (Maybe a)
b3 :: IO (Maybe a)
b3 = fmap Just b2 `mplus` return Nothing
```

```haskell
ghci> b1
*** Exception: user error (exception)
ghci> b3
Nothing
```

The exception is caught by `mplus`, so we no longer have the same value as we started with. That is a counterexample that the two types are isomorphic.

You might say that they are isomorphic if you disregard exceptions. That is, you might say that `IO (Maybe a)` expressions will never throw exceptions. But can you guarantee that? In the end, you're mapping all exceptions to `Nothing`, which is a lossy conversion.

Assuming you are okay with the lossy conversion and exception throwing, the consequences of having every failure indicated with an exception include, at least, (1) the type does not clearly indicate that the function can fail and (2) the users of the function must catch exceptions to avoid predictable errors. [This recent article](https://lexi-lambda.github.io/blog/2016/06/12/four-months-with-haskell/) had some good points on the author's experience with exception handling.

You have also suggested using `MaybeT IO a` instead of `IO (Maybe a)`:

```haskell
-- Yet another initial value
c1 :: IO (Maybe a)
c1 = throwIO $ userError "exception"

-- Convert to MaybeT IO a
c2 :: MaybeT IO a
c2 = MaybeT c1

-- Convert back to IO (Maybe a)
c3 :: IO (Maybe a)
c3 = runMaybeT c2
```

This is more clearly isomorphic, with `MaybeT` and `runMaybeT` being the witnesses of the isomorphism. The downside of having every function in `MaybeT` is the overhead of converting back and forth to `IO`.

**Comment by 2426021684** [comment]
@spl 
```
λ> let b1 = throwIO $ userError "exception" :: IO (Maybe a)
λ> :t b1
b1 :: IO (Maybe a)
λ> let b2 = b1 & liftIO >>= mfromMaybe
λ> :t b2
b2 :: (MonadPlus m, MonadIO m) => m b
λ> let b3 = runMaybeT b2
λ> :t b3
b3 :: MonadIO m => m (Maybe a)
λ> b1
*** Exception: user error (exception)
λ> b2
*** Exception: user error (exception)
λ> b3
*** Exception: user error (exception)
```
Exceptions appear to be preserved.

**Comment by 2426021684** [comment]
They are not isomorphic. Because a `MonadPlus` can contain more than 1 value. But, as long as the `MonadPlus` contains 1 or 0 values they are isomorphic.

**Comment by spl** [comment]
@2426021684:

> Exceptions appear to be preserved.

Hmm. I see now that you're changing the definition of `mzero` using the different `MonadPlus` instances for `IO` and `MaybeT`. You're changing the monad that `m` is instantiated to. You can see this with the following:

```haskell
f1 :: (MonadIO m, MonadPlus m) => m ()
f1 = mzero

f2 :: MonadIO m => m (Maybe ())
f2 = runMaybeT f1
```

In GHCi:

```
ghci> f1
*** Exception: user error (mzero)
ghci> f2
Nothing
```

Since GHCi coerces the monad to `IO` in these cases, in `f1 :: IO ()`, `mzero` throws an exception, whereas in `f2 :: IO (Maybe ())`, `mzero` returns `Nothing`.

At the risk of repeating myself, using `(MonadIO m, MonadPlus m) => m a` as the return type for functions puts you in a sort of default position of having exceptions thrown. Even if you can use `runMaybeT` to avoid that (and it only avoids the exceptions thrown by `mzero :: IO a`), it takes more knowledge and work, so it is less likely to be done. 

The default approach should, in general, involve types that clearly indicate their results, failure included. There are exceptions to the rule, of course, but those “exceptions” should probably be the kind that are (a) rarely thrown and (b) catastrophic to the application.

Perhaps the argument should start with the identification that many of the `Maybe`s are never `Nothing`. I think that's what @hamishmack is saying in https://github.com/ghcjs/ghcjs-dom/issues/48#issuecomment-241239442, now that I reread it. If that's the case, I think you're better off changing the type from `m (Maybe a)` to `m a` instead of using `MonadPlus` to “hide” an `mzero` that you don't expect.

**Comment by hamishmack** [comment]
Every function that the IDL files say can return null or undefined now has 4 wrappers.

`getElementById` returns `Maybe Element`
`getElementById_` discards the result
`getElementByIdUnsafe` returns `Element` or uses `HasCallStack` to give a nice error (including the call site location)
`getElementByIdUnchecked` returns an Element that will be invalid if the element was not found (you will probably get an error later when you try to use it).

The `_` and `Unchecked` can be used with `nextAnimationFrame` without causing unwanted redraws.
